# Generated by Django 2.1 on 2018-08-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=200)),
                ('register_date', models.DateTimeField(verbose_name='date published')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
